version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"   # Jenkins web UI
      - "50000:50000" # Jenkins agent connections
    volumes:
      - jenkins_home:/var/jenkins_home  # persistance des données Jenkins
      - /var/run/docker.sock:/var/run/docker.sock  # permet à Jenkins d'utiliser Docker
    user: root

volumes:
  jenkins_home:
